### PR TITLE
Added optional form parameters to support FIFO in SQS.

### PR DESCRIPTION
**Pull request by lucasdina**

### CODE REVIEW

**Comment by lucasdina** [comment]
Unsure as to why the build failed on the second run. Any insight would be helpful.
https://travis-ci.com/github/agilord/aws_client/jobs/317934153

**Comment by Schwusch** [comment]
@lucasdina If you run `dartfmt -w .` in the `aws_client` folder, there will be changes to `sqs.dart`.
The builds are very strict about style and fails on any diffs after running dartfmt.
Run the command and push the changes, and it will pass :)

**Comment by Schwusch** [comment]
Unrelated, but have you considered using the [generated package](https://pub.dev/packages/aws_sqs_api)? 
It seems to [support what you're looking for](https://pub.dev/documentation/aws_sqs_api/latest/sqs-2012-11-05/SQS/sendMessage.html).

**Comment by lucasdina** [comment]
@Schwusch I don't know how I missed the SQS stuff in the generated package. Looks like that does exactly what I need. I'm going to leave this PR open in case you still want to merge it, otherwise feel free to close it if there is no need for it. Thanks :)

**Comment by isoos** [comment]
Let's not waste a good PR :)

**Comment by isoos** [comment]
@lucasdina: Thanks again for the PR. Please let us now how the generated SQS library works for you, and we accept PRs for the generator too :)

**Pull request merged**
