### PR TITLE
Copy LICENSE file to generated projects.

### PR DESCRIPTION
**Pull request by isoos**

### CODE REVIEW

**Comment by Schwusch** [comment]
I'm a license illiterate. Is this alright considering the sources we are generating from?  

What are the placeholders intended to be filled with?

**Comment by isoos** [comment]
> Is this alright considering the sources we are generating from?

Good point, I'll need to take a second look on how this works on other projects. It is likely that we need to link to the source files too.

**Comment by isoos** [comment]
Updated PR to copy the AWS SDK license to the generated packages. PTAL.

**Comment by Schwusch** [comment]
LGTM.

**Pull request merged**
