### PR TITLE
Fixed top-level enum serialization. [patch]

### PR DESCRIPTION
**Pull request by isoos**
Generated code for #176.

### CODE REVIEW

**Comment by isoos** [comment]
@Schwusch: I'm wondering: is `.toValue()` the correct call here? Shouldn't we call `?.toValue()` instead?

**Comment by Schwusch** [comment]
> Shouldn't we call ?.toValue() instead?

You're right, there's probably no harm in doing it for required parameters too.
I can update the PR.

**Comment by isoos** [comment]
> I can update the PR.

Yeah, please push a commit, I'll update the generated code.

**Comment by isoos** [comment]
You can push a commit into this PR too - I think... But I can edit the code, no problem...

**Comment by isoos** [comment]
To be clear, I'll do it.

**Pull request merged**
