### PR TITLE
Migrate to null safety

### PR DESCRIPTION
**Pull request by xvrh**
This is my attempt to migrate the generated apis to null-safety

This was not easy!

I had to make a lot of changes and some changes may be controversial and need to be adjusted based on feedbacks.

For instance, I choose to make Map and List elements non-nullable. I think it gives a more user-friendly API. But it also mean that we can no longer send and receive null elements in list and map.
I would like to learn the API that are affected by this limitation and try to find a way to "opt-in" the nullability rather than make all APIs upfront nullable.
(I think googleapis package has the same question: https://github.com/google/googleapis.dart/issues/200)
5 tests in the generated test suite needed adjustments in the expectations because of this.

Also I decided to drop json_serializable (see #293). I think it's a good time and it was a lot easier to unify the serialization methods.

I would really appreciate real-world feedback from usage.

Last thing, I plan to migrate document_client in a follow up pull request.

### CODE REVIEW

**Comment by isoos** [comment]
You are a hero! I've randomly sampled a few files (in generator, generated and shared), and those look great to me.

> For instance, I choose to make Map and List elements non-nullable. I think it gives a more user-friendly API. But it also mean that we can no longer send and receive null elements in list and map.

I think we can afford bold moves here, esp. if we do major version bumps. Let's see how this play out...

> I would really appreciate real-world feedback from usage.

Let's ship it! I think that is the only feasible way to get that :)

Maybe we can add an extra warning somewhere, or release the versions as a prerelease. But I don't think that everyone will upgrade at the same time, and hopefully we will get the feedback in time to correct for the larger gotchas...

**Review by isoos — APPROVED** [review]

**Review by Schwusch — APPROVED** [review]
> This was not easy!

You can say that again :) Well done!

> For instance, I choose to make Map and List elements non-nullable.

That will probably be true for the most part. In `aws-sdk-js-v3` the models are defined as [Smithy models](https://awslabs.github.io/smithy/1.0/spec/core/model.htm), where nullability is better defined, although not always super clear.
The model definitions in both v2 and v3 are mirroring the same services, although v2 is basically undocumented and does not contain nullability information, like [v3 does](https://awslabs.github.io/smithy/1.0/spec/core/type-refinement-traits.html#sparse-trait).

In the long run, we probably would need to parse v3 models in order to have correct types. I quickly checked a few v3 models, and they seem to be non-nullable for the most part.

Normally I'd like to see the non-generated code in a separate commit from the generated code, but since it passes the tests we might as well just get something out and take it from there.

Again, great job!

**Comment by xvrh** [comment]
Thanks for your feedbacks. I will merge it now and we will iterate on it.

@Schwusch 
> In the long run, we probably would need to parse v3 models in order to have correct types.

Yes, if this is the direction the `js-sdk` is taking, at some point this will be required. But it looks like a big effort too.

**Comment by Schwusch** [comment]
Mentioning #292 here for visibility.

**Pull request merged**
