### PR TITLE
Create a mono package version of all apis

### LINKED ISSUE #299: Reconsider one package vs. multiple packages
I'd like to re-open the discussion about single vs several packages.

I read the discussion of last year here: https://github.com/agilord/aws_client/issues/63
The main reason to split the apis in several packages was to prevent the documentation generation to timeout on pub.dev.

I personally think that the advantages of the single package option outweighs this small inconvenience.

**Pros of a single package:**
- Easier development (simplify code generator etc...)
- Easier publishing
- Easier to add/remove APIs
- A user of the library have immediately access to all the apis (like in JS and Python)
- Easier to work with git and dependency_overrides
- ...

**Cons:**
- Possibly no documentation on pub.dev (mitigated by publishing our own documentation)
- Some users may only use one API and don't want to download the code for the others?

## Proposal
Here is my rough idea on how we could possibly proceed

### New package
Publish a new package (`aws_client`?) that contains all the apis.

**Layout:**
```
lib/
  src/
    shared/ // Content of the shared_aws_api
    accessanalyzer/
      2019-11-01.dart // actual code
      2019-11-01.g.dart
  accessanalyzer/
    2019-11-01.dart // export src/accessanalyzer/2019-11-01.dart
    ...
README.md: generated list of all apis with a small description (ie. https://pub.dev/packages/googleapis)
CHANGELOG.md: hand-edited changelog with global improvements
```

### Migration
Publish a new version for all current packages with an updated README pointing to the new single-package.
Discontinue all the previously published packages on pub.dev

### Documentation
Mitigate the pub.dev timeout failure by publishing our own documentation and link to it in the README.
When we tag the repository, a Github Action runs dartdoc and upload the new doc on github.io.

Longer term: profile the execution of dartdoc on the package to understand how to speed it up (currently it takes 15 minutes on my mac with the `all_apis` package).

WDYT?

### PR DESCRIPTION
**Pull request by xvrh**
Fixes #299

Create a tool `dart bin/generate.dart generate-single-package` that will copy all the APIs in a single package (`aws_client`).
Everything remains the same but we can now also publish a single package with all the APIs easily.

First commit are the changes in the generator, second commit the generated package.

Happy to discuss the idea more if needed.

If you agree with this change, then I will proceed to publish a new version of `aws_client` to pub.dev.

### CODE REVIEW

**Comment by isoos** [comment]
@xvrh: Could you please check the total size of the files? IIRC pub.dev has a limit of 100MB, are we close to it?

This will also mean that we'll have a better release story, but pub.dev is unlikely to generate dartdoc for it for now. Not that we need it necessarily, and we can also generate it ourselves and self-host it on github...

**Comment by xvrh** [comment]
@isoos the `lib/` directory is 85MB uncompressed, ~12.5MB zipped.

`cloc` output:
```sh
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Dart                           780         216113         745559        1519390
```

**Comment by xvrh** [comment]
https://dart.dev/tools/pub/publishing :

`Your package must be smaller than 100 MB after gzip compression. If it’s too large, consider splitting it into multiple packages, using a .pubignore file to remove unnecessary content, or cutting down on the number of included resources or examples.`

So I think we are good on that front.

**Comment by isoos** [comment]
> Documented 362 public libraries in 847.1 seconds

There is also a size limit for those, any chance you haven't deleted it yet to measure it?

**Review by isoos — APPROVED** [review]

**Comment by xvrh** [comment]
`doc/` is `5.27 GB` uncompressed 😱 (`925MB` compressed)

**Comment by isoos** [comment]
> doc/ is 5.27 GB uncompressed

IIRC 2GB uncompressed is the limit...

**Comment by xvrh** [comment]
@isoos if you still agree with my plan can you add [package:aws_client](https://pub.dev/packages/aws_client) to the publisher aws-dart.agilord.com?

Also, can we use the (awesome) automated publishing from Github? That means we will have to add git tags the repository. Any recommendations on this?

**Comment by isoos** [comment]
> can you add package:aws_client to the publisher aws-dart.agilord.com?

done.

> Also, can we use the (awesome) automated publishing from Github? That means we will have to add git tags the repository. Any recommendations on this?

The default is good for us I think (also I think it is the same as the one you've got in puppeteer's repo).
We could add workflows, but I don't think it is necessary.

**Comment by isoos** [comment]
> We could add workflows, but I don't think it is necessary.

Edit: We could add approval workflows, but I don't think it is necessary.

**Pull request merged**
