### PR TITLE
Generate all the APIs with version v2.1635.0 of the AWS SDK

### LINKED ISSUE #423: Add support for Bedrock Runtime API
Hi there!

First of all, thanks for your work, the project looks great.

I'm the maintainer of [LangChain.dart](https://github.com/davidmigloz/langchain_dart) and I've been researching how to integrate AWS Bedrock to support running inference on the models it supports.

Currently, there isn't a Dart AWS Bedrock client that I know of. But given the infrastructure you've developed, I think it will be fairly straightforward to add support for it to your project.

AWS Bedrock has 4 APIs:
- [bedrock](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock)
- [bedrock-agent](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-agent)
- [bedrock-agent-runtime](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-agent-runtime)
- [bedrock-runtime](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-runtime)

In my case, I'm only interested in the Bedrock runtime, which is the one that allows you to run inference on the models.

Let me know if it's doable and how I can help with the implementation.

### PR DESCRIPTION
**Pull request by xvrh**
First commit is the changes in the `generator` (new fields)
Second commit is the generated files
Third commit is the version bump & changelog

Fixes #423

### CODE REVIEW

**Review by isoos — APPROVED** [review]
💯 thank you!

**Comment by isoos** [comment]
I'm wondering: should I now discontinue the individual packages on `pub.dev`?

**Comment by xvrh** [comment]
@isoos decision up to you ;-)
I don't plan to upload new version myself (it takes too long) 😀

**Comment by xvrh** [comment]
I'll publish the new version now.

**Pull request merged**
