### PR TITLE
Don't sign operations with authtype == 'none'

### PR DESCRIPTION
**Pull request by simonbuchan**
Partial fix for #316 in that this doesn't let you *not* have credentials yet, it will simply not use them for operations qualified as such. I'm successfully using these generated packages with `AwsClientCredentials(accessKey: 'UNUSED', secretKey: 'UNUSED')`, so at least there's that.

I believe *strictly* this is wrong, as e.g. you can use IAM policy conditions on the otherwise unnecessarily signed request? So I'm happy to leave this as draft until I have a way for the `credentials` parameter to be specified as explicitly unsigned.

### CODE REVIEW

**Comment by isoos** [comment]
I like this, but let's ask other ideas too. /cc @Schwusch @xvrh

**Comment by Schwusch** [comment]
I think it's a good idea and LGTM 👍

**Comment by Schwusch** [comment]
Travis tests says:
> [SEVERE] json_serializable:json_serializable on lib/model/error.dart:
Generator cannot target libraries that have not been migrated to null-safety.

Not sure what that's about

**Comment by simonbuchan** [comment]
> Not sure what that's about

I guessed on my last PR #317 that it was that the `shared_aws_client` package is being pulled from `pub.dev`, since that's not null safe yet?

Perhaps CI testing with `generate --dev` would fix that, and other PRs where both the shared and generated packages change together, like this one.

**Comment by Schwusch** [comment]
> the shared_aws_client package is being pulled from pub.dev

Oh right, that's inconvenient. That test is a flawed approach, and is covered by the Github Action we have.
Then I say we merge, and remove the Travis test later :+1:

**Pull request merged**
